services:
  pgadmin:
    container_name: ddev-${DDEV_SITENAME}-pgadmin
    image: dpage/pgadmin4:latest
    restart: "no"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
    - "pgadmin-data:/var/lib/pgadmin"
    - "./pgadmin/servers.json:/pgadmin4/servers.json"
    - "./pgadmin/.pgpass:/home/pgadmin/.pgpass" # TODO: set `chmod 600 /home/pgadmin/.pgpass && chown pgadmin /home/pgadmin/.pgpass`
    expose:
      - "80"
    environment:
    - PGADMIN_DEFAULT_EMAIL=db@ddev.site
    - PGADMIN_DEFAULT_PASSWORD=db
    - VIRTUAL_HOST=pgadmin.$DDEV_HOSTNAME
    - HTTP_EXPOSE=80:80
    - HTTPS_EXPOSE=443:80
    # TODO: This should allow logging in without a password, but doesn't work for some reason. See
    # - SERVER_MODE=False
    healthcheck:
      interval: 120s
      timeout: 2s
      retries: 1
    depends_on:
      - db

volumes:
  pgadmin-data:
